In [44]:
import numpy as np
import time


In [45]:
l1= [2, 43, 3,]
l2= [2, 5, 2]



In [5]:
import numpy as np
import time


In [6]:
l1= [1, 2, 4]
l2= [4, 4, 6]


In [110]:
list(zip(l1, l2))
list(zip(l1, l2

NameError: name 'l1' is not defined

using numpy array

In [10]:
import numpy as np 
import time



In [12]:
add = l1 + l2

[1, 2, 4, 4, 4, 6]

In [14]:
type(list)

list

In [23]:
l1= [2, 43, 3,]
l2= [2, 5, 2]

pylist = list(zip(l1,l2))

In [30]:
type(pylist)

list

In [34]:
l1= np.array([2, 43, 3,])
l2= np.array([2, 5, 2])


nplist = l1 + l2 

In [31]:
type(nplist)

list

In [60]:
np.array([1, 4, 3, 2, 8, 9, "pankaj"])
np.array([[2, 7, 3], [5, 6, 9]])

array([[2, 7, 3],
       [5, 6, 9]])

In [65]:
np.array(
    [
        [1, 2, 4],
        [3, 5, 2],
    ],
    [
        [1, 2, 4],
        [5, 3, 2]])
        
    

TypeError: Field elements must be 2- or 3-tuples, got '[1, 2, 4]'

In [66]:
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [67]:
type(arr_3d)

numpy.ndarray

In [70]:
arr_3d.shape

(2, 2, 3)

In [4]:
import numpy as np
import sys

list_data = list(range(100))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 85600 bytes
NumPy array size: 800 bytes


In [2]:
import numpy as np

In [3]:
l1 = np.array([23, 42, 43])

In [10]:
l1 = np.array([[1, 3, 5],
               [4, 4, 3],
               [2, 2, 2],
               [4, 3, 2]])

In [11]:
l1

array([[1, 3, 5],
       [4, 4, 3],
       [2, 2, 2],
       [4, 3, 2]])

In [13]:
flat = l1.flatten()

In [14]:
flat

array([1, 3, 5, 4, 4, 3, 2, 2, 2, 4, 3, 2])

In [15]:
flat = l1.flatten()

In [16]:
flat

array([1, 3, 5, 4, 4, 3, 2, 2, 2, 4, 3, 2])

In [20]:
print(flat[6])

2


In [29]:
print(flat[4], flat[0])

4 1


In [31]:
print(flat[4], flat[3])

4 4


In [33]:
flat[2:]

array([5, 4, 4, 3, 2, 2, 2, 4, 3, 2])

In [38]:
flat[::3]

array([1, 4, 2, 4])

In [84]:
slicing = np.array([[0,1,2,3],
         [4,5,6,7],
         [8,9,10,11],
         [12,13,14,15]]
        )

In [85]:
flat_arr =slicing.flatten()

In [86]:
flat_arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [89]:
flat_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
flat_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
flat_arr[::4]

array([ 0,  4,  8, 12])

In [94]:
b = flat_arr[0:10]

In [95]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
b[6] = 66

In [98]:
flat_arr

array([ 0,  1,  2,  3,  4,  5, 66,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

In [106]:
flat_arr

array([  0,   1,   2,   3,   4, 555,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [103]:
slice_arr = flat_arr[0:10]

In [113]:
slice_arr

array([  0,   1,   2,   3,   4, 555,   6,   7,   8,   9])

In [115]:
slice_arr[5].copy = 555

AttributeError: 'numpy.int64' object attribute 'copy' is read-only

In [116]:
arr=flat_arr

In [ ]:
flat

In [117]:
arr

array([  0,   1,   2,   3,   4, 555,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [133]:
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
#fancy indexing

In [146]:
arr[[2, 3,2]]

array([2, 3, 2])

In [147]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

#Create a 3×3 array filled with random numbers and print its shape.

In [157]:
arr=np.array([
    [2,3,5],
    [5,4,9],
    [5,9,5],
])

print(arr.shape)

(3, 3)


#Convert an array of floats [1.1, 2.2, 3.3] into integers


In [159]:
arr=np.array([1.1, 2.2, 3.3])


In [175]:
arr=np.array([1.1, 2.2, 3.3])

int_float=arr.astype(int)

print(int_float)

[1 2 3]


Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].


In [198]:
arr= np.array([1, 2, 3, 4, 5, 6])

number = arr[arr%2==0]
print(number)


[2 4 6]


Reshape a 1D array of size 9 into a 3×3 matrix.

In [225]:
         
matrix = arr.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

matrix = np.array([
          arr[0:3], 
    
          arr[3:6], 
          arr[6:9]
])
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

matrix = np.array([
    arr[0:3],
    arr[3:6],
    arr[6:9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Use boolean masking to filter numbers greater than 50 in an array.

In [18]:
import random
import numpy as np 

In [36]:
import random 
arr_random = random.sample(range(0,100),20)
print(arr_random)
print(type(arr_random))





[81, 12, 20, 56, 66, 4, 13, 10, 53, 68, 91, 79, 8, 77, 67, 2, 26, 75, 64, 76]
<class 'list'>


In [37]:
arr = np.array([arr_random])
print(arr)
print(type(arr))

[[81 12 20 56 66  4 13 10 53 68 91 79  8 77 67  2 26 75 64 76]]
<class 'numpy.ndarray'>


In [58]:
arr = np.array([arr_random])

mask = arr>50
print(arr[mask])



[81 56 66 53 68 91 79 77 67 75 64 76]


In [39]:
arr = np.array([arr_random])

[array([[ True, False, False,  True,  True, False, False, False,  True,
          True,  True,  True, False,  True,  True, False, False,  True,
          True,  True]])]

In [46]:
arr = np.array([10, 20, 30, 40, 50])
  # [30 40 50]

[30 40 50]


In [72]:
import numpy as np 
arr = np.array([[81, 12, 20],
                [56, 66, 4,],
                [13, 10, 53]])

In [74]:
arr.shape

(3, 3)

In [77]:
arr[2]

array([13, 10, 53])

In [80]:
np.sum(arr, axis=1)

array([113, 126,  76])

In [83]:
np.sum(arr, axis=1)

array([113, 126,  76])

In [204]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

matrix = np.array([
          arr[0:3], 
    
          arr[3:6], 
          arr[6:9]
])
print(matrix)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
MSE 0.08500000000000002
Binary Cross-Entropy: 0.32844691758328565
Categorical Cross-Entropy: 1.487890207904797
Kullback-Leibler Divergence: 0.09695352463929671


In [97]:
arr = np.array([[10, 20, 30],
               [40, 50,43],
               [30, 20,23]]
              )

In [98]:
arr

array([[10, 20, 30],
       [40, 50, 43],
       [30, 20, 23]])

In [109]:
print(arr[0][2])

30


In [110]:
print(arr[0,2])

30


In [112]:
print(arr[0:2,1:2])

[[20]
 [50]]


In [113]:
print(arr[0:2, 1:2])

[[20]
 [50]]


### ndexing in 3d arrays

In [173]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], #layer 0
                  [[7, 8, 9], [10, 11, 12]],  #layer 1
                  [[88, 99, 4], [30, 31, 3]],
                ])  #layer 2x
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(3, 2, 3)


In [174]:
print(arr3D[2,0,2])



4


In [175]:
print(arr3D[:,1,:])

[[ 4  5  6]
 [10 11 12]
 [30 31  3]]


In [176]:
arr[:,0,:] = 0


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [156]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[88, 99,  4],
        [30, 31,  3]]])

### homogeneous
Common Data Types in NumPy:
int32, int64: Integer types with different bit sizes.

float32, float64: Floating-point types with different precision.

bool: Boolean data type.

complex64, complex128: Complex number types.

object: For storing objects (e.g., Python objects, strings).

In [181]:
import numpy as np 
arr= np.array([34, 43, 22, 322])
print(arr)

[ 34  43  22 322]


In [184]:
arr.dtype

dtype('int64')

In [187]:
arr.astype("float64")

array([ 34.,  43.,  22., 322.])

In [199]:
import random 
arr = random.sample(range(10,100000),50000)

In [200]:
arr= np.array([arr])

In [201]:
type(arr)

numpy.ndarray

In [202]:
print(arr)

[[26965 85059 42536 ...  5873 94060 87798]]


In [203]:
arr.astype("float64")

array([[26965., 85059., 42536., ...,  5873., 94060., 87798.]])

In [19]:
import numpy as np

In [9]:
arr = np.array([1, 3, 2, 3])

In [10]:
arr.astype("float64")

array([1., 3., 2., 3.])

In [17]:
arr = np.array([1, 3, 3])

In [18]:
arr.astype("float64")

array([1., 3., 3.])

In [17]:
import random 

arr = (random.sample(range(1, 2000000), 20000))

In [38]:
import random 


arr = np.array(random.sample(range(200, 2000000), 20000))

In [33]:
arr.astype("float64")

array([ 28084., 115220.,  70812., ...,  19145.,  71994.,  89389.])

In [15]:
type(arr)

numpy.ndarray

In [32]:
import time

start_time = time.perf_counter()

# ---------  code here ----------

arr.astype("float64")

# -------------------------------

end_time = time.perf_counter()
print(f"Execution time: {end_time - start_time:.6f} seconds")


Execution time: 0.000055 seconds


In [43]:
import time

start_time= time.time()

arr.astype("float64")

end_time= time.time()

print(f"your execution time is {end_time - start_time }")

your execution time is 6.222724914550781e-05


In [42]:
import random 


arr = np.array(random.sample(range(100, 200), 20))

In [44]:
arr

array([154, 157, 100, 171, 149, 158, 151, 123, 152, 191, 186, 126, 193,
       139, 104, 112, 198, 170, 128, 127])

In [45]:
arr[1]

np.int64(157)

In [48]:
arr_float = arr.astype("float64")

In [49]:
arr_float[1]

np.float64(157.0)

In [77]:
print(arr_float)
print(print(arr))

print(arr_float.dtype)

[154. 157. 100. 171. 149. 158. 151. 123. 152. 191. 186. 126. 193. 139.
 104. 112. 198. 170. 128. 127.]
[1. 3. 2. 3.]
None
float64


In [70]:
arr2 = np.array(random.sample(range(100, 200), 20), dtype="float16").   

In [73]:
arr.nbytes                         # Memory Usage

32

In [74]:
arr = np.array([1, 3, 2, 3], dtype="float32") 

In [76]:
type(arr)

numpy.ndarray

In [80]:
arr= np.array(["apple", "mango", "chuku"], dtype="U10")     #string number

In [81]:
arr

array(['apple', 'mango', 'chuku'], dtype='<U10')

In [85]:
arr= np.array(["apple", "mango", "chuku"])             #string list not afficaint in numpy

In [86]:
type(arr)

numpy.ndarray

In [95]:
arr= np.array([1+2j, 3+4j], dtype="complex64")         #complex number

In [94]:
type(arr)

numpy.ndarray

In [107]:
arr = np.array([{ "name": "pankaj"}, [1, 3, 3], "hello"], dtype="object")        #dictonary object 

In [106]:
print(arr)

[{'name': 'pankaj'} list([1, 3, 3]) 'hello']


### Python, loops are typically slow because:

Python’s interpreter: Every iteration of the loop requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.
High overhead: Each loop iteration in Python involves additional overhead for function calls, memory access, and index management.
While Python loops are convenient, they don’t take advantage of the optimized memory and computation that libraries like NumPy provide.

Example: Looping Over Arrays in Python

In [6]:
import numpy as np 

arr = np.array([2, 42, 1, 1,])

result = []


for num in arr:
    result.append(num**2)

print(result)

[np.int64(4), np.int64(1764), np.int64(1), np.int64(1)]


In [8]:
import numpy as np

result =[]
arr = np.array([2, 42, 1, 1,])

for num in arr:
    result.append(num**2)

print(result)



[np.int64(4), np.int64(1764), np.int64(1), np.int64(1)]


In [15]:
import numpy as np 

empty_list = []

list1 = np.array([2, 42, 1, 1,])


for square_num in list1:
    empty_list.append(square_num**2)

print(empty_list)


[np.int64(4), np.int64(1764), np.int64(1), np.int64(1)]


In [19]:
arr = np.array([2, 2, 4, 7,])

square_list = arr **2 
print(square_list)

[ 4  4 16 49]


Vectorization: Fixing the Loop Problem
Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. This is made possible by NumPy’s optimized C-based backend that executes operations in compiled code, which is much faster than Python loops.

Vectorized operations are also more readable and compact, making your code easier to maintain.

Example: Vectorized Operation
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

Here, the operation is applied to all elements of the array simultaneously, and it's much faster than looping over the array.

Why is it Faster?
Low-level implementation: NumPy’s vectorized operations are implemented in C (compiled language), which is much faster than Python loops.
Batch processing: NumPy processes multiple elements in parallel using SIMD (Single Instruction, Multiple Data), allowing multiple operations to be done simultaneously.


In [20]:
arr = np.array([2, 2, 4, 7,])

square_list = arr **2 
print(square_list)

[ 4  4 16 49]


### Broadcasting: Scaling Arrays Without Extra Memory
Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

Example: Broadcasting with Scalar
Broadcasting is often used when you want to perform an operation on an array and a scalar value (e.g., add a number to all elements of an array).

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

Here, the scalar 10 is "broadcast" across the entire array, and no extra memory is used.



In [22]:
arr = np.array([2, 2, 4, 7,])

new_arr = arr+10.  # Here, the scalar 10 is "broadcast" across the entire array, and no extra memory is used.
new_arr

array([12, 12, 14, 17])

In [23]:
arr1 = np.array ([1, 2, 4])
arr2 = np.array ([6, 3, 3])

addition = arr1 + arr2 
print(addition)

[7 5 7]


## Normalizing Data Using Broadcasting

In [46]:
import random 

list1 = random.sample(range(10, 200), 15)
print(list1)

l2 = list1[0:3], list1[4:7], list1[8:11], list1[12:15]
l2


[120, 196, 87, 88, 43, 70, 68, 173, 186, 183, 59, 36, 17, 132, 162]


([120, 196, 87], [43, 70, 68], [186, 183, 59], [17, 132, 162])

In [30]:
print(list)

[169, 125, 16, 119, 171, 122, 108, 181, 118, 132, 13, 144, 128, 14, 37, 136, 44, 55, 43, 137]


In [51]:
dataset= np.array([[12, 19, 87], 
                   [43, 70, 68], 
                   [16, 18, 59], 
                   [17, 13, 16],
                   [15, 19, 12]])



In [85]:
first_i_want_mean = dataset.mean(axis=0)
second_i_want_std = dataset.std(axis=0)


normalized_data = (dataset - first_i_want_mean ) / second_i_want_std 
print(normalized_data)


[[ 0.42910544  1.02328375 -0.17266853]
 [-0.73023207 -1.51728281 -0.64134025]
 [ 1.42282331  0.76116181 -0.86334264]
 [-1.12169669 -0.26716275  1.67735141]]


In [86]:
empyt_list=[]

axis_1 = dataset.mean(axis = 1)
axis_int = axis_1.astype(int)

for i in axis_int:
    empyt_list.append(axis_int)
    print(i)

134
60
142
103


In [112]:
import random 
import numpy as np


arr = np.array(random.sample(range(10, 50),10))
print(arr)


[33 24 21 30 35 26 25 39 37 44]


In [113]:
int_no = np.mean(arr)             #mean
print(int_no ,  "\n")

print(int_no.astype(int))

31.4 

31


In [124]:
np.std(arr)

np.float64(7.059745037889116)

In [125]:
np.var(arr)

np.float64(49.84)

In [126]:
np.min(arr)

np.int64(21)

In [127]:
np.max(arr)

np.int64(44)

In [128]:
np.sum(arr)

np.int64(314)

In [129]:
np.prod(arr)           # Compute the product of all elements in an array.

np.int64(720719279280000)

In [123]:
np.median(arr)


np.float64(31.5)

In [132]:
np.percentile(arr, 40)

np.float64(28.4)

In [136]:
np.argmin(arr)

np.int64(2)

In [138]:
np.argmax(arr)

np.int64(9)

In [139]:
np.corrcoef(arr1, arr2)

array([[ 1.        , -0.18898224,  1.        ],
       [-0.18898224,  1.        , -0.18898224],
       [ 1.        , -0.18898224,  1.        ]])

In [141]:
np.unique(arr)

array([21, 24, 25, 26, 30, 33, 35, 37, 39, 44])

In [143]:
np.diff(arr)

array([-9, -3,  9,  5, -9, -1, 14, -2,  7])

In [146]:
 #Compute the n-th differences of an array.

print(np.diff(arr))
  #Compute the cumulative sum of an array.

print(np.cumsum(arr))

 #Create an array with evenly spaced numbers over a specified interval.

print(np.linspace(0, 10, 5) ) # 5 numbers from 0 to 10

#Compute the natural logarithm of an array.

print(np.log(arr))

 #Compute the exponential of an array.

print(np.exp(arr))



[-9 -3  9  5 -9 -1 14 -2  7]
[ 33  57  78 108 143 169 194 233 270 314]
[ 0.   2.5  5.   7.5 10. ]
[3.49650756 3.17805383 3.04452244 3.40119738 3.55534806 3.25809654
 3.21887582 3.66356165 3.61091791 3.78418963]
[2.14643580e+14 2.64891221e+10 1.31881573e+09 1.06864746e+13
 1.58601345e+15 1.95729609e+11 7.20048993e+10 8.65934004e+16
 1.17191424e+16 1.28516001e+19]


In [171]:
# Create a 4×4 matrix with values from 1 to 16 and reshape it

import numpy as np
n_list=[]
for i in range(1, 17):
    n_list.append(i)

print(n_list)
numpy_array = np.array(n_list)
matrix = numpy_array.reshape(4,4)
matrix



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
# Extract all even numbers from a given NumPy array.
import numpy as np
numpy_array = np.arange(1,20)

even = numpy_array[numpy_array%2==0]
print(even)

[ 2  4  6  8 10 12 14 16 18]


In [14]:
# Replace all odd numbers in an array with -1.
import numpy as np
numpy_array = np.arange(1,21)

# Select elements that are odd (remainder of 1 when divided by 2)
# and assign them the value -1
numpy_array[numpy_array % 2 != 0] = -1

print(numpy_array)


[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


In [19]:
# Find the mean, median, and standard deviation of an array.
#import numpy as np
#numpy_array = np.arange(1,21)
#print(numpy_array)


numpy_array = np.array([ 1,  2,  3 , 4 , 5 , 6 , 7 , 8 , 9 ,10, 11, 12 ,13, 14 ,15, 16, 17, 18 ,19 ,20])
print(f"mean of array is {np.mean(numpy_array)}\nmedian of array is {np.median(numpy_array)}\nstandard deviation of array is {np.std(numpy_array)} ")

mean of array is 10.5
median of array is 10.5
standard deviation of array is 5.766281297335398 


In [36]:
# Multiply two 3×3 matrices.

# import numpy as np


# matrix1 = np.arange(1,10)
# matrix2 = np.arange(11,20)

# print(matrix1.reshape(3,3))
# print(matrix2.reshape(3,3))




A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
Multiply = matrix1 @ matrix2
Multiply

np.int64(735)

In [56]:
# Create a 2D array and swap two rows.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix[0 , 1] 


np.int64(2)

In [66]:
# Normalize a NumPy array (scale values between 0 and 1).

numpy_array = np.array([ 1,  2,  3 , 4 , 5 , 6 , 7 , 8 , 9 ,10])

min_=np.min(numpy_array)
print(min)

max_=np.max(numpy_array)
print(max)

normalization = (numpy_array-min_) /( max_ - min_ )
normalization


1
10


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [70]:
#Find indices where elements are greater than a given value.

given=5

numpy_array = np.array([ 1,  2,  3 , 4 , 5 , 6 , 7 , 8 , 9 ,10])

indices = numpy_array[numpy_array>5], np.argmin(numpy_array)



(array([ 6,  7,  8,  9, 10]), np.int64(0))

In [71]:
# Compute the dot product of two arrays.

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using np.dot()
result = np.dot(a, b)

# Or using the @ operator
# result = a @ b

print(result) 

32


In [85]:
# Create a maticx  with random values and find the sum of each row and column


matrix= np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


row= matrix.sum(axis=1)
colum = matrix.sum(axis=0)
print(row, colum)

[ 6 15 24] [12 15 18]


In [ ]:
Write a function using NumPy to compute Euclidean distance between two vectors

In [86]:
import numpy as np

def create_checkerboard(n=8):
    # Initialize an n x n array with zeros
    board = np.zeros((n, n), dtype=int)
    
    # Fill with 1s: 
    # [1::2, ::2] selects every other row starting from index 1, 
    # and every other column starting from index 0.
    board[1::2, ::2] = 1
    
    # [::2, 1::2] selects every other row starting from index 0, 
    # and every other column starting from index 1.
    board[::2, 1::2] = 1
    
    return board

print(create_checkerboard(8))


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
Solve a system of linear equations using NumPy.

In [88]:
import numpy as np
import pandas as pd

# Set a seed for reproducibility
np.random.seed(42)

# Generate a large dataset: 1,000,000 rows and 10 columns
data = np.random.rand(1_000_000, 10)

# Create a DataFrame with column names
df = pd.DataFrame(data, columns=[f'Feature_{i+1}' for i in range(10)])
df

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10
0,0.374540,0.950714,0.731994,0.598658,0.156019,0.155995,0.058084,0.866176,0.601115,0.708073
1,0.020584,0.969910,0.832443,0.212339,0.181825,0.183405,0.304242,0.524756,0.431945,0.291229
2,0.611853,0.139494,0.292145,0.366362,0.456070,0.785176,0.199674,0.514234,0.592415,0.046450
3,0.607545,0.170524,0.065052,0.948886,0.965632,0.808397,0.304614,0.097672,0.684233,0.440152
4,0.122038,0.495177,0.034389,0.909320,0.258780,0.662522,0.311711,0.520068,0.546710,0.184854
...,...,...,...,...,...,...,...,...,...,...
999995,0.136494,0.975974,0.167103,0.484240,0.922823,0.505476,0.563155,0.604786,0.603848,0.400024
999996,0.679977,0.250804,0.967151,0.803170,0.151645,0.092126,0.822532,0.691671,0.194507,0.567588
999997,0.954097,0.294182,0.666740,0.692612,0.704384,0.981713,0.355471,0.055201,0.319454,0.582437
999998,0.742370,0.378104,0.799182,0.077733,0.648529,0.415797,0.975016,0.402638,0.851827,0.588404


In [109]:
# Given a large array (1M rows), remove duplicate rows efficiently (no loops).

import numpy as np
import random
import pandas as pd

data = np.random.rand(1_000_000, 3)
df = pd.DataFrame(data, columns=["colums_1", "colums_2", "colums_3"])
diag = np.diagonal(data)
diag

array([0.16159773, 0.05161378, 0.21838336])